### ISSUE TITLE
Is this module still maintained?

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/puppet-ssh_keygen#10]
Hi everybody,

I'm one of the [Vox Pupuli](voxpupuli.org) maintainers. I wanted to ask you if this module is still maintained. Support for Puppet4 is lacking, and several people asked us if we could maintain this module. Are you interested in migrating it to the Vox Pupuli namespace?

**Comment by carlossg** [comment]
sure

**Comment by bastelfreak** [comment]
Hi @carlossg, I just noticed that you are already part of the Vox Pupuli github org, so you should have the permissions to migrate this module into our namespace. We documented the migration process at https://voxpupuli.org/docs/, let us know if you've any questions. We're available almost 24/7 in the #voxpupuli IRC channel on freenode.

**Comment by carlossg** [comment]
@bastelfreak moved, it's all yours now!
