### ISSUE TITLE
Finish migration to VoxPupuli

### ISSUE THREAD

**Issue by alexjfisher** [voxpupuli/puppet-ssh_keygen#12]
- [x] Update README (remove massive THIS MODULE HAS BEEN MOVED TO VOXPUPULI warning)
- [x] Add README badges
- [x] Sync labels
- [x] Add LICENSE file (so that github license detection works)
- [x] Update metadata.json
  - [x] name
  - [x] version (2.0.0-rc0 ?)
  - [x] source
  - [x] license (Use proper identifier for apache license)
  - [x] project_page
  - [x] puppet 4 version requirement?
- [x] rubocop fixes (if people want to start creating PRs for these before the modulesync that can sometimes help)
- [x] Add to modulesync_config
- [x] Add to plumbing
- [x] modulesync
- [x] Puppet 4 data types?
- [x] Remove v999.999.999 tag.  (This will probably upset github-changelog-generator otherwise)
- [x] Release 2.0.0 (release PR including changelog)
- [x] Thank @carlossg !

**Comment by wyardley** [comment]
- README / LICSENSE: #14 
- Metadata: #13 
- Rubocop: #15 
- Modulesync: #17 
- Data types: #16

**Comment by wyardley** [comment]
Thanks @carlossg
