### ISSUE TITLE
Error: Syntax error using the module 

### ISSUE THREAD

**Issue by mativillagra** [voxpupuli/puppet-ssh_keygen#31]
Hi. 

I will like to use this module to create ssh-keys to a user called provision, I have a Puppetfile with the code mod 'puppet-ssh_keygen', '2.0.1' and used librarian-puppet v1.5.0 to install the module. 

I try to used but I received an error.  

Any advice will be great Thanks ins advance. 

## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 3.8.7 
- Ruby: ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux] 
- Distribution: Red Hat Enterprise Linux Server release 6.9 (Santiago)
- Module version: 'puppet-ssh_keygen', '2.0.1'

## How to reproduce (e.g Puppet code you use)

class provision_linux

{

ssh_keygen { 'provision': }

}

## What are you seeing

Error: Syntax error at 'Optional'; expected ')' at /root/repos/slave-base/puppet/modules/ssh_keygen/manifests/init.pp:42 on node vm21
Error: Syntax error at 'Optional'; expected ')' at /root/repos/slave-base/puppet/modules/ssh_keygen/manifests/init.pp:42 on node vm21

## Any additional information you'd like to impart

File  /root/repos/slave-base/puppet/modules/ssh_keygen/manifests/init.pp 

define ssh_keygen (
  **Optional[String] $user     = undef,**
  Enum['rsa', 'dsa'] $type   = 'rsa',
  Optional[Integer] $bits    = undef,
  Optional[String] $home     = undef,
  Optional[String] $filename = undef,
  Optional[String] $comment  = undef,
  Optional[String] $options  = undef,
) {

**Comment by juniorsysadmin** [comment]
@mativillagra Puppet 3 and Ruby 1.8.7 are not supported in any form. See: https://voxpupuli.org/blog/2016/12/22/putting-down-puppet-3/
